### ISSUE TITLE
关于此项目的问题

### ISSUE THREAD

**Issue by cakota6462** [Harry-zklcdc/go-bingai-pass#2]
@Harry-zklcdc 大佬好，请问这个项目该怎么使用？可以和隔壁Hansimov大佬的bing-chat-api一起使用吗？

**Comment by Harry-zklcdc** [comment]
理论上可以，使用方法就是 API 请求，抓一下包应该就懂了，最近没啥时间写使用教程，有空的时候写一下吧

**Comment by Harry-zklcdc** [comment]
部署方式 [https://github.com/Harry-zklcdc/go-proxy-bingai#人机验证服务器](https://github.com/Harry-zklcdc/go-proxy-bingai?tab=readme-ov-file#%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81%E6%9C%8D%E5%8A%A1%E5%99%A8)
