### ISSUE TITLE
问问直接服务器部署的方法

### ISSUE THREAD

**Issue by lm379** [Harry-zklcdc/go-bingai-pass#6]
看了下dockerfile似乎是容器内部署了个ubuntu系统，然后在ubuntu内安装edge来实现的，那我想直接在ubuntu的服务器上部署应该怎么做呢

**Comment by Harry-zklcdc** [comment]
参考 Dockerfile 里面的命令

https://github.com/Harry-zklcdc/go-bingai-pass/blob/main/Dockerfile

**Comment by lm379** [comment]
那大佬这些环境变量呢，我写入到/etc/profile或者.bashrc中？
ENV SCREEN_WIDTH=1360
ENV SCREEN_HEIGHT=1020
ENV SCREEN_DEPTH=24
ENV SCREEN_DPI=96
ENV SE_START_XVFB=true
ENV DISPLAY=:99.0
ENV DISPLAY_NUM=99

ENV PORT=7860
ENV HEADLESS=false
ENV BROWSER_BINARY=/usr/bin/microsoft-edge
# ENV PASS_TIMEOUT=10
# ENV CHROME_PATH=/opt/google/chrome
ENV XDG_CONFIG_HOME=/tmp/edge
ENV XDG_CACHE_HOME=/tmp/edge

**Comment by Harry-zklcdc** [comment]
我用的是 supervisor 去管理的，你参考一下 supervisor 怎么添加环境变量即可

改这个配置文件即可 https://github.com/Harry-zklcdc/go-bingai-pass/blob/main/supervisor.conf
