### ISSUE TITLE
反复人机验证

### ISSUE THREAD

**Issue by cutexiaoguigui** [Harry-zklcdc/go-bingai-pass#8]
使用Cloudflare Worker 一键部署，在验证时反复弹出人机验证框
![image](https://github.com/Harry-zklcdc/go-bingai-pass/assets/131460253/412afb5f-a76d-42c1-b717-ef1ab8a3f3f7)
![image](https://github.com/Harry-zklcdc/go-bingai-pass/assets/131460253/d051c9bc-2e01-45d1-b5b6-e9114f8e23d4)

https://github.com/Harry-zklcdc/go-bingai-pass/assets/131460253/fa6be2cf-b9bd-41a7-8af0-d0fe11caea08

Windows11 谷歌125.0.6422.142（正式版本） （64 位）

**Comment by Harry-zklcdc** [comment]
CF 反复的话，就一键重置，刷新 MUID
